### ISSUE TITLE
Leftover elements on dragging nodes

### ISSUE THREAD

**Issue by karan-kang** [Blazor-Diagrams/Blazor.Diagrams#143] opened 2021-10-07 14:15 UTC
Version Information
```
.NET Framework:         5.0
Blazor Hosting:         Server     
Z.Blazor.Diagram:       2.1.5   
Browser:                Edge 94.0.992.38               
```

![image](https://user-images.githubusercontent.com/1234394/136401778-97654f7d-f1e6-4ceb-9277-610dc369ad32.png)

**Comment by zHaytam** [comment] 2021-10-07 14:18
Hello,
I will need more information if possible.

- What is the content of your nodes (HTML or SVG)?
- Are those leftovers caused by nodes or links?
- How many elements (nodes/links) do you have in the diagram?

If you can provide a reproducible little example project, that would help me a lot!

**Comment by 314159265meow** [comment] 2021-11-02 10:56
Hi, 
I noticed this problem as well. It's not easy to reproduce reliably and seems to occur only at a very low zoom level. To me it looks like a browser render problem, maybe related to non-integer coordinates. So far I have no good idea how to fix it.

I managed to reproduce it at your demo page https://blazor-diagrams.zhaytam.com/demos/custom-group
![Animation2](https://user-images.githubusercontent.com/13624874/139833893-0dc4b53a-827e-46cb-a8c4-3083c0c4ee81.gif)

Maybe this helps somehow.

**Comment by zHaytam** [comment] 2021-11-02 10:59
I can also "sometimes" reproduce it in a very low zoom level and only when using CSS borders. When I remove the borders or replace it by something like `box-shadow`, then it doesn't happen.

Unfortunately I don't know exactly what the issue is, but the library doesn't do anything to cause it as far as I know...

**Comment by zHaytam** [comment] 2021-11-02 11:57
@314159265meow Could you please try adding the following CSS and telling me if it still happens? Because for me, and for some reason I don't know, this fixes it:

```css
.diagram-canvas {
    backface-visibility: hidden;
}
```

**Comment by 314159265meow** [comment] 2021-11-02 12:17
This fixes it for me as well. "In the old days" this was a trick to force the activation of hardware acceleration, not sure exactly how this works today. 

I found another way to work around the issue. In the example of the custom group, it works if I set a border and a transparent outline, like this:

```
.group.custom {
  border: 2px solid black;
  outline: 6px solid transparent;
}
```

Also this problem doesn't seem to be related to this library, I managed to reproduce it in a single HTML file with 3 divs and a few lines of JavaScript.

**Comment by zHaytam** [comment] 2021-11-02 12:18
Could you please send me the code you reproduced it with?

**Comment by 314159265meow** [comment] 2021-11-02 12:22
Sure, on the page you can use the mouse wheel to zoom and this produces the same artifacts for me.
[index.zip](https://github.com/Blazor-Diagrams/Blazor.Diagrams/files/7460538/index.zip)

**Comment by zHaytam** [comment] 2021-11-10 08:19
Closing this since it's not related to the library, thanks!

**Closed by zHaytam** 2021-11-10 08:19 UTC
Labels: need-user-input
